config/routes.rb
Rails.application.routes.draw do
  get 'scrap/index' => 'scrap#index', as: 'scrap'
  get 'scrap/all_links' => 'scrap#all_links', as: 'all_links'
  root 'scrap#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/scrap_controller.rb
class ScrapController < ApplicationController
  before_action :connect_apkpure, except: [:welcome]
  def index
    require 'csv'
    apk = Hash.new
    json_response = []
    page_data = @page.css('.top-list')
    csv_response = CSV.generate do |csv|
      csv << ['name','icon_image','download_link_url']
      page_data.each do |page|
        page.css('li').each do |p|
          apk['name'] = p.css('.title-dd').text
          apk['icon_image'] = p.css('img').attribute('src').value
          apk['download_link'] = (@url + p.css('.down a').first.attribute('href').value)
          csv << [apk['name'], apk['icon_image'], apk['download_link']]
          json_response << apk
        end
      end
    end
    if params[:req_type] == 'json'
      render json: json_response
    else
      render json: csv_response
    end
  end
  
  def welcome
    
  end
  
  def all_links
    a = []
    b = Hash.new
#    binding.pry
#    a << @page.links_with.to_a
# binding.pry
#    @page.links_with.each do |l,index|
#     
#      b[index] = l
#      a << b
#    end
#    render raw: @page.links_with
render nothing: true
  end
  
  private
  def connect_apkpure
    require 'mechanize'
    mechanize = Mechanize.new
    @url = 'https://apkpure.co/'
    @page = mechanize.get(@url)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrap_helper.rb
module ScrapHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrapapkpure</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrap/index.html.erb
<h1>Scrap#index</h1>
<p>Find me in app/views/scrap/index.html.erb</p>

app/views/scrap/welcome.html.erb
Hi,
<%= link_to "CSV response",scrap_path,method: :get, title: "Click to fetch the csv data of apkpure.co" %>
<%= link_to "Json response",scrap_path(req_type: 'json'), method: :get, title: "Click to fetch the json data of apkpure.co" %>
<%#= link_to "All Links", all_links_path, method: :get, title: "Click to fetch all links of apkpure.co" %>